import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center p-24">
          {" "}
          <nav>
            <ul className="flex gap-4">
              <Link href={"/"}>
                <li>Home</li>
              </Link>
              <Link href={"/about"}>
                <li>About</li>
              </Link>
            </ul>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
